/**
 * Mock data for lookupMaps tests
 * Provides predictable test data without loading from files
 */

// What needs fixing (PLUMBING_ISSUE_ITEM_LOOKUP)
export const mockPlumbingIssueItems = {
  'toilet': { dispatchCategory: 'fixture' },
  'commode': { dispatchCategory: 'fixture' },
  'water_closet': { dispatchCategory: 'fixture' },
  'wc': { dispatchCategory: 'fixture' },
  'sink': { dispatchCategory: 'fixture' },
  'basin': { dispatchCategory: 'fixture' },
  'vanity': { dispatchCategory: 'fixture' },
  'faucet': { dispatchCategory: 'fixture' },
  'spigot': { dispatchCategory: 'fixture' },
  'silcock': { dispatchCategory: 'fixture' },
  'shower': { dispatchCategory: 'fixture' },
  'bathtub_faucet': { dispatchCategory: 'fixture' },
  'tub_drain': { dispatchCategory: 'component' },
  'tub_overflow': { dispatchCategory: 'component' },
  'garbage_disposal': { dispatchCategory: 'fixture' },
  'disposal': { dispatchCategory: 'fixture' },
  'food_waste_disposer': { dispatchCategory: 'fixture' },
  'hose_bib': { dispatchCategory: 'fixture' },
  'pipe': { dispatchCategory: 'component' },
  'water_heater': { dispatchCategory: 'appliance' },
  'dishwasher': { dispatchCategory: 'appliance' },
  'dish_washer': { dispatchCategory: 'appliance' },
  'dish_machine': { dispatchCategory: 'appliance' },
  'washing_machine': { dispatchCategory: 'appliance' },
  'washer': { dispatchCategory: 'appliance' },
  'sump_pump': { dispatchCategory: 'appliance' },
  'drain': { dispatchCategory: 'component' },
  'sewer': { dispatchCategory: 'component' },
  'water_main': { dispatchCategory: 'component' },
  'main_water_line': { dispatchCategory: 'component' },
  'street_water': { dispatchCategory: 'component' },
  'gas_line': { dispatchCategory: 'component' },
  'attic': { dispatchCategory: 'fixture' },
  'fill_valve': { dispatchCategory: 'component' },
  'flapper': { dispatchCategory: 'component' }
}

// Where damage is visible (DAMAGE_PLACE_LOOKUP)
export const mockDamagePlaceLookup = {
  'bathroom': { category: 'room' },
  'kitchen': { category: 'room' },
  'bedroom': { category: 'room' },
  'basement': { category: 'room' },
  'cellar': { category: 'room' },
  'garage': { category: 'room' },
  'laundry_room': { category: 'room' },
  'utility_room': { category: 'room' },
  'laundry_area': { category: 'room' },
  'upstairs': { category: 'area' },
  'downstairs': { category: 'area' },
  'attic': { category: 'area' },
  'roof_space': { category: 'area' },
  'crawl_space': { category: 'area' },
  'exterior': { category: 'area' },
  'outside': { category: 'area' },
  'outdoor': { category: 'area' },
  'ceiling': { category: 'surface' },
  'wall': { category: 'surface' },
  'floor': { category: 'surface' },
  'foundation': { category: 'structure' },
  'bathtub': { category: 'fixture' },
  'tub': { category: 'fixture' },
  'jacuzzi': { category: 'fixture' },
  'soaking_tub': { category: 'fixture' }
}


export const mockSymptoms = {
  'leaking': { category: 'symptom', urgency: 'medium' },
  'leak': { category: 'symptom', urgency: 'medium' },
  'dripping': { category: 'symptom', urgency: 'low' },
  'clogged': { category: 'symptom', urgency: 'medium' },
  'jammed': { category: 'symptom', urgency: 'medium' },
  'bursting': { category: 'symptom', urgency: 'high' },
  'flooding': { category: 'symptom', urgency: 'high' },
  'no water': { category: 'symptom', urgency: 'high' },
  'running': { category: 'symptom', urgency: 'medium' },
  'overflowing': { category: 'symptom', urgency: 'high' },
  'making noise': { category: 'symptom', urgency: 'low' },
  'flush': { category: 'symptom', urgency: 'medium' },
  'not working': { category: 'symptom', urgency: 'high' },
  'not draining': { category: 'symptom', urgency: 'medium' },
  'broken': { category: 'symptom', urgency: 'high' },
  'malfunctioning': { category: 'symptom', urgency: 'medium' },
  'failed': { category: 'symptom', urgency: 'high' },
  'backed up': { category: 'symptom', urgency: 'high' },
  'burst': { category: 'symptom', urgency: 'high' },
  'smell': { category: 'symptom', urgency: 'medium' },
  'noise': { category: 'symptom', urgency: 'low' },
  'water': { category: 'symptom', urgency: 'medium' },
  'leaking': { category: 'symptom', urgency: 'medium' },
  'dripping': { category: 'symptom', urgency: 'low' },
  'not draining': { category: 'symptom', urgency: 'medium' },
  'clogged': { category: 'symptom', urgency: 'medium' },
  'broken': { category: 'symptom', urgency: 'high' },
  'not heating': { category: 'symptom', urgency: 'high' },
  'not cleaning': { category: 'symptom', urgency: 'medium' },
  'not spinning': { category: 'symptom', urgency: 'medium' },
  'burst': { category: 'symptom', urgency: 'high' },
  'gas': { category: 'symptom', urgency: 'high' },
  'outside': { category: 'symptom', urgency: 'medium' },
  'outdoor': { category: 'symptom', urgency: 'medium' },
  'exterior': { category: 'symptom', urgency: 'medium' },
  'stopped': { category: 'symptom', urgency: 'high' },
  'everywhere': { category: 'symptom', urgency: 'high' },
  'froze': { category: 'symptom', urgency: 'high' },
  'utility': { category: 'symptom', urgency: 'medium' },
  'area': { category: 'symptom', urgency: 'medium' },
  'floor': { category: 'symptom', urgency: 'medium' },
  'washer': { category: 'symptom', urgency: 'medium' },
  'hookups': { category: 'symptom', urgency: 'low' },
  'low': { category: 'symptom', urgency: 'low' },
  'pressure': { category: 'symptom', urgency: 'medium' },
  'loose': { category: 'symptom', urgency: 'low' },
  'spigot': { category: 'symptom', urgency: 'low' },
  'tap': { category: 'symptom', urgency: 'low' },
  'turn': { category: 'symptom', urgency: 'medium' },
  'off': { category: 'symptom', urgency: 'medium' },
  'line': { category: 'symptom', urgency: 'medium' },
  'backing': { category: 'symptom', urgency: 'high' },
  'sewage': { category: 'symptom', urgency: 'high' },
  'smell': { category: 'symptom', urgency: 'medium' },
  'odor': { category: 'symptom', urgency: 'medium' },
  'main': { category: 'symptom', urgency: 'high' },
  'shut': { category: 'symptom', urgency: 'high' },
  'valve': { category: 'symptom', urgency: 'high' },
  'meter': { category: 'symptom', urgency: 'medium' },
  'gas': { category: 'symptom', urgency: 'high' },
  'heating': { category: 'symptom', urgency: 'high' },
  'cooling': { category: 'symptom', urgency: 'medium' },
  'hvac': { category: 'symptom', urgency: 'medium' },
  'roof': { category: 'symptom', urgency: 'high' },
  'rafters': { category: 'symptom', urgency: 'medium' },
  'insulation': { category: 'symptom', urgency: 'low' },
  'crawlspace': { category: 'symptom', urgency: 'medium' },
  'foundation': { category: 'symptom', urgency: 'high' },
  'vent': { category: 'symptom', urgency: 'medium' },
  'duct': { category: 'symptom', urgency: 'medium' },
  'dryer': { category: 'symptom', urgency: 'low' },
  'venting': { category: 'symptom', urgency: 'medium' },
  'condensation': { category: 'symptom', urgency: 'low' },
  'sweating': { category: 'symptom', urgency: 'low' },
  'pipes': { category: 'symptom', urgency: 'medium' },
  'fixture': { category: 'symptom', urgency: 'medium' },
  'connections': { category: 'symptom', urgency: 'low' },
  'supply': { category: 'symptom', urgency: 'high' },
  'feed': { category: 'symptom', urgency: 'high' },
  'tank': { category: 'symptom', urgency: 'medium' },
  'tankless': { category: 'symptom', urgency: 'medium' },
  'pilot': { category: 'symptom', urgency: 'high' },
  'ignition': { category: 'symptom', urgency: 'high' },
  'thermocouple': { category: 'symptom', urgency: 'medium' },
  'burner': { category: 'symptom', urgency: 'medium' },
  'element': { category: 'symptom', urgency: 'medium' },
  'thermostat': { category: 'symptom', urgency: 'medium' },
  'dishwasher': { category: 'symptom', urgency: 'medium' },
  'not cleaning': { category: 'symptom', urgency: 'medium' },
  'not draining': { category: 'symptom', urgency: 'medium' },
  'washing machine': { category: 'symptom', urgency: 'medium' },
  'not spinning': { category: 'symptom', urgency: 'medium' },
  'not filling': { category: 'symptom', urgency: 'medium' },
  'hose': { category: 'symptom', urgency: 'low' },
  'bibb': { category: 'symptom', urgency: 'low' },
  'spicket': { category: 'symptom', urgency: 'low' },
  'sillcock': { category: 'symptom', urgency: 'low' },
  'backflow': { category: 'symptom', urgency: 'high' },
  'preventer': { category: 'symptom', urgency: 'high' },
  'pressure reducing': { category: 'symptom', urgency: 'medium' },
  'regulator': { category: 'symptom', urgency: 'medium' },
  'expansion': { category: 'symptom', urgency: 'low' },
  'tank': { category: 'symptom', urgency: 'low' },
  'circulating': { category: 'symptom', urgency: 'low' },
  'pump': { category: 'symptom', urgency: 'medium' },
  'recirculation': { category: 'symptom', urgency: 'low' },
  'instant': { category: 'symptom', urgency: 'medium' },
  'hot': { category: 'symptom', urgency: 'high' },
  'cold': { category: 'symptom', urgency: 'medium' },
  'warm': { category: 'symptom', urgency: 'low' },
  'tepid': { category: 'symptom', urgency: 'low' },
  'scalding': { category: 'symptom', urgency: 'high' },
  'temperature': { category: 'symptom', urgency: 'medium' },
  'fluctuating': { category: 'symptom', urgency: 'low' },
  'inconsistent': { category: 'symptom', urgency: 'low' },
  'crack': { category: 'symptom', urgency: 'high' },
  'propane': { category: 'symptom', urgency: 'high' },
  'natural': { category: 'symptom', urgency: 'medium' },
  'crawlspace': { category: 'symptom', urgency: 'high' },
  'under': { category: 'symptom', urgency: 'medium' },
  'house': { category: 'symptom', urgency: 'medium' },
  'spigot': { category: 'symptom', urgency: 'low' },
  'loose': { category: 'symptom', urgency: 'low' },
  'tap': { category: 'symptom', urgency: 'low' },
  'tank': { category: 'symptom', urgency: 'medium' },
  'no hot': { category: 'symptom', urgency: 'high' },
  'second': { category: 'symptom', urgency: 'low' },
  'first': { category: 'symptom', urgency: 'low' },
  'master': { category: 'symptom', urgency: 'low' },
  'guest': { category: 'symptom', urgency: 'low' }
}

export const mockSymptomGroups = [
  {
    name: 'water_issues',
    symptoms: ['leaking', 'dripping', 'bursting', 'flooding'],
    category: 'water_leak',
    urgency: 'high'
  },
  {
    name: 'drainage_issues',
    symptoms: ['clogged', 'backed up', 'slow drain'],
    category: 'drainage',
    urgency: 'medium'
  }
]
